mysql_host: 192.168.42.136
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30616165383239663961306230653330633630306339623533396564343464356137343330626461
          6633356262343330313566653730316339666366333063310a366436383133356264323763383966
          36643263333531643361343266316162663139666632333933313466396565623335396133633432
          3030613733663037610a636136343832663666303266356262346336653032313330626666366563
          3664
exporter_user: prometheus
exporter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31366230303465313839306439653837616138653634306230366632643933643962656333306461
          3664383735323735383637336661613431393738313462660a363137333566323635623234376339
          34316564373239333562626331313530313839663366353164363564646362616665653931303134
          3438613461366632350a333966653263323865393439343034623933623563323134313938633833
          3766
dns_forwarders:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9
  - 9.9.9.10
dns_local_addresses:
  - 192.168.42.0/24
  - 127.0.0.0/8
domain: hitec.io
