mysql_host: ellawerthan-1
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30616165383239663961306230653330633630306339623533396564343464356137343330626461
          6633356262343330313566653730316339666366333063310a366436383133356264323763383966
          36643263333531643361343266316162663139666632333933313466396565623335396133633432
          3030613733663037610a636136343832663666303266356262346336653032313330626666366563
          3664
mysql_replication_user: replication
mysql_replication_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34616163336365383935333066303064386137376335383337373936376366623038656562613236
          6161643164366664343033353130326435623965356265310a643831373730653064303933346135
          33303631663131373233653433616462356365346431643537363163386130313264373930386261
          3035353464313733310a623932653534366232316237323132643737326531613765363466666439
          3332
exporter_user: prometheus
exporter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31366230303465313839306439653837616138653634306230366632643933643962656333306461
          3664383735323735383637336661613431393738313462660a363137333566323635623234376339
          34316564373239333562626331313530313839663366353164363564646362616665653931303134
          3438613461366632350a333966653263323865393439343034623933623563323134313938633833
          3766
domain: hitec.io
a_records:
  - subdomain: backup
    ip: 192.168.42.156
dns_cnames:
  - cname: influxdb
    real: "{{ groups['influxdb'][0] }}"
  - cname: prometheus
    real: "{{ groups['prometheus'][0] }}"
ns_transfer_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65666332356462353863636637343939313339373834633635396135333362333531353835636231
          6161313038346363616333313266323833333336373463330a363338383930363833623036353562
          37633230643262366661396361623436393034393565633663336234653437323962663037353730
          3538656334343961300a386465366466376633646130383465666161646630353135646632643338
          63643933373563343961333862333139363263396462656538613865633165643630386266386234
          6431613637316461643139653164313631353537373538643963
ns_update_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37633665333338303635346232623830383664653730306538346163306431326439336337363339
          6565393664333466393363396336343161623339636362300a653166316131613239383633356133
          65643337653139656436383734623839653636613530643065666336613664353636326462636636
          3336383261316433360a386639376666616339343536663439323036303632306139323639346231
          33333436383137633537366165623162656634656339363632303666643536646361643937343537
          6366306634323537383264363535366136636531313661643962
dns_local_addresses:
  - 192.168.42.0/24
  - 127.0.0.0/8
dns_forwarders:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9
  - 9.9.9.10
company_name: hitec
grafana_port: 3001
agama_port: 8001
pinger_user: pinger
pinger_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32376362396138323833663337643133653265636165643732616263666432613232303235646537
          6339316538303930346535346338373835353262663833310a333433633461646339616466313361
          64643965326566666631646630316264336232306561346662346639626464653530613833326336
          6666373361653337620a643539626361623235366163326630623663383062343163323665653966
          3563
mysql_backup_user: backup
mysql_backup_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38383666366661643938323762636632623739353636666534616536353233656632386362643263
          3138376435643933393063633935333366336163393065350a616231353530346538366234653965
          63323664346639613639363536393631343233646634636335343735353037363736316634343065
          3338366635313133370a303265366637393630643134326336373239376637363463623063303138
          3331